NHSDigital/ndr_import

- lib/ndr_import/mapper.rb
- test/mapper_test.rb
Currently, `Mapper#standard_mapping(mapping_name, column_mapping)` can mutate both the incoming `column_mapping`, as well as the configured standard mapping for `mapping_name`.
The former is a recent regression [3c7f827d17aa], but the I think the latter is long-standing behaviour. I'm not sure if is desirable though – for example, `#validate_line_mappings` runs `#standard_mapping` before the `column_mapping` is used; we might experience unexpected behaviour with repeated attempts to mutate the same mapping.
@timgentry, could you review this change please? I'm not super-familiar with the mapper.
> # Standard mappings should not mutate with use

- lib/ndr_import/mapper.rb
@timgentry, @ollietulloch:
I've had a go at cleaning up some of the logic in mapper.rb. Playing around with the `Benchmark` library suggests that it's around 5% faster in general, but massively faster (orders of magnitude) when standard mappings are used - rubyprof showed as much as 99.5% of total time spend on merging standard mappings.
> Mapper refactor

- lib/ndr_import/file/delimited.rb
- lib/ndr_import/helpers/file/delimited.rb
@timgentry, are you aware of the reason behind these clauses? I've had a frustrating hour or so working out why my file wasn't mapping...
> Remove minimum row length from delimited importers

- lib/ndr_import/mapper.rb
@timgentry ,
`replace_before_mapping` seems like a real hotspot. I've made some tweaks to reduce allocations, which is helping with replace-heavy mappings.
However, I wonder if we shouldn't implement `:pre_map` or something? Things like
```yaml
replace:
- !ruby/regexp /\Aincoming\z/i: 'type_a'
- !ruby/regexp /\Aincoming_2\z/i: 'type_a'
- !ruby/regexp /\Aanother_incoming\z/i: 'type_b'
- !ruby/regexp /\Aanother_incoming_2\z/i: 'type_b'
```
, which are applied using `gsub!`, will be much less efficient than (something like):
```yaml
pre_map:
incoming: type_a
incoming_2: type_a
another_incoming: type_b
another_incoming_2: type_b
```
and could be done with:
```ruby
mapped_value = pre_map.fetch(mapped_value, mapped_value)
```
> # Reduce allocations on replace-heavy map

- lib/ndr_import/table.rb
- test/table_test.rb
Continuing on from #9, I wonder if this branch doesn't solve the issue that @khunter68 saw without negatively affecting existing behaviour.
Previously, `fail_unless_header_complete` was used to stop if a matching header row hadn't been found in the N `header_rows` specified. However, this logic would never even be reached if one of the N rows was not of the correct length (even if the N as a whole indeed contained a valid row) – i.e. problems could arise of the header block was "non-cuboid".
@timgentry - thoughts?
> Don't validate header prematurely

- lib/ndr_import/helpers/file/xml.rb
- ndr_import.gemspec
@timgentry, in 47394f8790c802fe you constrained the `nokogiri` dependency because of "breaking changes".
There is a CVE which means we should upgrade; a test was failing which I've now fixed, but did you have broader concerns about what was "breaking" ?
> # bump nokogiri, for CVE-2017-9050

- lib/ndr_import/non_tabular/column_mapping.rb
- test/non_tabular/table_test.rb
As discussed in #21, this PR will `strip` non-tabular captured values by default.
> Strip non tabular captured values by default.

- lib/ndr_import.rb
- lib/ndr_import/mapper.rb
- lib/ndr_import/missing_field_error.rb
- ndr_import.gemspec
- test/mapper_test.rb
This PR adds the ability to specify ActiveRecord-like validations in field mappings, starting with the equivalent of https://guides.rubyonrails.org/active_record_validations.html#presence
> Add validations to field mappings

- lib/ndr_import/table.rb
- test/table_test.rb
> control ndr_table serialise order with encode_with method

- CHANGELOG.md
- lib/ndr_import/table.rb
- test/table_test.rb
Currently, if the klass is embedded array, it will mapped to ` { 'do_not_capture' => true }`.
This PR fix the above issue, therefore the yaml mapping can looks like the following:
```
--- !ruby/object:NdrImport::Table
list_of_klasses: &list_of_klasses
- SomeKlass#1
- SomeKlass#2
- SomeKlass#3
- SomeKlass#4
- SomeOtherKlass
canonical_name: somename
row_identifier: uuid
header_lines: 0
footer_lines: 0
columns:
- column: one
klass:
- *list_of_klasses
- AdditionalKlass
```
> allow `klass` in the column level mapping to be embedded array

- Gemfile
- gemfiles/Gemfile.rails50
- gemfiles/Gemfile.rails51
- gemfiles/Gemfile.rails52
The shim Gemfile references to `ooxml_decrypt` are no longer needed as I have published the gem on RubyGems. There will be a bump to `v1.0.0` if my PR is accepted, which is why I have left off a version requirement.
> ooxml_decrypt is now on RubyGems

- README.md
- bin/console
- bin/setup
- exe/pdf_acro_form_to_yaml
- exe/pdf_to_text
- exe/word_to_text
- ndr_import.gemspec
Moving data loader tools into the gem makes them easier to maintain and ensures that they are always run using the correct dependency versions.
> Data loader tools

- CHANGELOG.md
- lib/ndr_import/file/xml.rb
- lib/ndr_import/helpers/file/xml.rb
- lib/ndr_import/helpers/file/xml_streaming.rb
- lib/ndr_import/universal_importer_helper.rb
- ndr_import.gemspec
- test/file/xml_test.rb
- test/helpers/file/xml_streaming_test.rb
- test/resources/claims_utf16be_but_isnt.xml
This PR is opened for discussion, at this stage.
I've added code to allow XML documents to be streamed by Nokogiri. It makes efforts to be as efficient as possible, whilst still aiming to support the myriad of encoding weirdness scenarios that has caused headaches in the past. To that end, it'll sometimes have to drop down into a slight less efficient slurp/stream hybrid strategy.
I've switched the `File::Xml` class to stream XML by default, and provided a `slurp: true` option to allow access to the legacy behaviour.
The streaming works by chugging through the XML as a SAX parser would, and keeping a micro-DOM built to represent how far into the document's DOM structure the cursor has descended. This micro-DOM allows for XPath to still be used to detect when and element of interest has …
> Add ability to stream XML files

- ndr_import.gemspec
As discussed, we should remove legacy version restriction for spreadsheet gem.
@joshpencheon
> remove version restriction to spreadsheet gem

- .travis.yml
- lib/ndr_import/csv_library.rb
- lib/ndr_import/helpers/file/delimited.rb
This fixes deprecations emitted on Ruby 2.7.0
> # ruby 2.7: ensure keyword args are properly splatted

- lib/ndr_import/universal_importer_helper.rb
This PR removes a line of code that was left in by accident in #54, sorry!
There should be no observable behaviour differences; no CHANGELOG entry necessary.
> Remove unused code from universal import helper.

- CHANGELOG.md
- lib/ndr_import/helpers/file/xml.rb
- test/helpers/file/xml_test.rb
- test/resources/malformed.xml
- test/resources/with-control-chars.xml
Related to internal ticket 25592, this PR proposes escaping control characters found in XML data, before handing it to Nokogiri / @libxml@ for parsing.
The background is that XML 1.0 generally [mustn't contain control characters](https://www.w3.org/TR/2006/REC-xml-20060816/Overview.html#charsets), and in XML 1.1 it's still [highly discouraged](https://www.w3.org/TR/2006/REC-xml11-20060816/#charsets). The data we tend to process is yet to provide a legitimate reason for preserving these control characters as-is downstream.
With other formats, we've settled on escaping control characters rather than stripping them, in case they are providing some semantic purpose (acting as a strange form of punctuation within a body of text, for example). However, they normally appear due to various …
> Escape control chars found in XML by default

- CHANGELOG.md
- lib/ndr_import/helpers/file/xml.rb
- lib/ndr_import/xml/control_char_escaper.rb
- test/helpers/file/xml_test.rb
- test/resources/with-control-char-references-in-cdata.xml
- test/resources/with-control-char-references.xml
- test/resources/with-non-control-char-references.xml
- test/xml/control_char_escaper_test.rb
This PR follows on from #60.
XML can also embed characters (outside of a `CDATA` section) using referencing schemes of `&#nnnn;` (decimal) and `&#xhhhh;` (hexadecimal). These are then substituted for their character values by the XML parser (in our case, `libxml`).
What this PR proposes doing is handling such sequences, when they represent invalid [XML 1.0] control characters, in the same way as the underlying control characters would be - i.e. escaped before the parser can trip over them.
Additionally, we avoid running the escaping routines until we've once observed the parser having problems; this allows us to make a "best effort" at preserving any unescaped sequences in `CDATA` sections (where they are allowed and wouldn't on their own cause parsing problems - as they then interpreted …
> Handle invalid control character references

- CHANGELOG.md
- ndr_import.gemspec
The 7zip library doesn't play nicely on linux at v1.2; this PR bumps the gem's minimum requirement to v1.3.
Projects using released versions of `ndr_import` can bump their own requirement manually, in the interim.
> Raise dependency on the 7zip gem

- .github/workflows/test.yml
As shown in PR #71,  there's an issue with the Actions config that prevents the tests running on PRs from forks.
This PR alters that config, so that the tests are triggered by any PR, and additionally against every commit _on master_.
* the ability to run tests against PRs coming from forks
* the ability for tests to have been pre-run for PRs coming from branches in this repo (i.e., while the PR is being authored).
> Run test workflow against PRs

- test/file/pdf_test.rb
- test/file/registry_test.rb
- test/helpers/file/pdf_test.rb
This PR fixes white space test failures on ruby 2.6x and 2.7x
A further PR will be needed to address the errors on ruby 3.1.1
> # Fix test failures resulting from Nokogiri bump (CVE-2022-24836)

- .gitignore
- .rubocop.yml
- LICENSE.txt
- README.md
- docs/_config.yml
- docs/inbuilt-cleaning-methods.md
- docs/standard-yaml-mappings.md
- gemfiles/Gemfile.rails52
- ndr_import.gemspec
This replaces all the references to Public Health England with NHS Digital, except for the `.github/CODEOWNERS` which remains the same, for now.
> Replaced references to PHE with NHS Digital

- lib/ndr_import/table.rb
- test/non_tabular/table_test.rb
Store `significant_mapped_fields` hash with ` NdrImport::Table` meta data in YAML mappings.
The can then be used in record depulication in external systems
> Store `significant_mapped_fields` hash in NdrImport::Tables

- ndr_import.gemspec
The `seven_zip_ruby` gem is unsupported, causing failures with GitHub Actions on Ruby 3.1.
`seven-zip` is a forked gem which supports more recent compilers.
> Replace unsupported seven_zip_ruby gem with seven-zip fork.

- CHANGELOG.md
- lib/ndr_import/version.rb
The XML enhancements introduce a breaking change that is not backward compatiable, so this is a major version bump.
> Bump to v11.0.0

- .github/workflows/test.yml
- CHANGELOG.md
- gemfiles/Gemfile.rails71
- ndr_import.gemspec
- test/test_helper.rb
Support Rails 7.1 and include it in the test matrix.
There are a number of Rails deprecation warnings triggered by this. I've tried but can't immediately find an easy way to fix them. For now, I'd rather we had Rails 7.1 support, and we can come back later to find good fixes for them (probably easier after we drop Rails 6.1 support).
> Support Rails 7.1

- CHANGELOG.md
- lib/ndr_import/file/excel.rb
- lib/ndr_import/helpers/file/excel.rb
- lib/ndr_import/helpers/file/xml.rb
This resolves deprecation warnings in Rails 7.0 about using `#to_s(:db)`.
It also fixes errors with the latest Nokogiri 1.16.0, when handling UTF-16 files which we've loaded and converted to UTF-8.
> Resolve Rails 7 deprecation messages.

- CHANGELOG.md
- code_safety.yml
- lib/ndr_import/version.rb
Fixes included:
* Resolve Rails 7 deprecation warnings
* Fix XML parsing with latest `nokogiri` 1.16.0
> Bump to v11.0.2

- CHANGELOG.md
- lib/ndr_import/xml/table.rb
- test/resources/sample_with_empty_nodes.xml
- test/xml/table_test.rb
`Xml::Table` checks that every xpath from an xml record is accounted for in column mappings, this means that empty nodes/sections require a column mapping
Example xml:
```
<root>
<record>
<no_relative_path value="A value"/>
<no_path_or_att>Another value</no_path_or_att>
<demographics>
<demographics_1>AAA</demographics_1>
<demographics_2 code="03">Inner text</demographics_2>
</demographics>
<pathology></pathology>
</record>
</root>
```
The `pathology` section is empty, but would require a column mapping, that is set to `do_not_capture`, so that `Xml::Table ` is happy the xpath is accounted for.
column mapping for `pathology`:
```
{ 'column' => 'pathology', 'klass' => 'SomeTestKlass',
'xml_cell' => { 'relative_path' => '' },
' do_not_capture' => true }
```
This PR only requires a column …
> XML table should gracefully handle empty nodes/elements

- CHANGELOG.md
- code_safety.yml
- lib/ndr_import/version.rb
Adds backward compatible functionality to `Xml::Table` to handle empty XML sections, without requiring stub column mappings
> Bump to v.11.1.0

- CHANGELOG.md
- docs/yaml-mapping-user-guide.md
- docs/zipped-field-mapping.md
- lib/ndr_import/mapper.rb
- test/mapper_test.rb
This PR adds column zipping functionality to the mapper, where 2 (or more) columns can have their string values split by a given `split_char` and then be zipped together in a prescribed order.
E.g. given this csv data
```
"title","value"
"species,colour,legs","dog,brown,4"
```
and this data:
```yaml
- column: title
mappings:
- field: zipped_field
zip_order: 1
split_char: ","
- column: value
mappings:
- field: zipped_field
zip_order: 2
```
This mapped_line would be produced:
```
{ "zipped_field"=>[["species", "dog"], ["colour", "brown"], ["legs", "4"]],
:rawtext=>{"title"=>"species,colour,legs", "value"=>"dog,brown,4"}}
```
> Add column/data zipping functionality

- CHANGELOG.md
- docs/capturing-column-names.md
- docs/regexp-column-names.md
- docs/yaml-mapping-user-guide.md
- lib/ndr_import/mapper.rb
- lib/ndr_import/table.rb
- test/mapper_test.rb
- test/table_test.rb
- test/vcf/table_test.rb
This PR adds two pieces of funtionality.
**Regex column names:**
This allows regex matching of column names where column name(s) may change slightly between files. If the regex matches the column header, the data will be mapped as usual. If the regex doesn't match, an invalid header error will be raised.
**Capturing column names as data**
Column names may contain data themselves, configuring `map_columname_to` at the column level will add the column name to each row of mapped data. It does not include any of the more sophisticated mapping functionality that other fields have, e.g. joining fields, cleaning values etc.
`vcf/table_test.rb` includes a test that combines both of these.
> Capture column names and Regex column name matching

- CHANGELOG.md
- lib/ndr_import/xml/masked_mappings.rb
The `Xml::Table` class attempts to augment column_mappings based on the data where there might be repeating sections/fields. It does this for each `line`, and so can be memory/compute intensive. 
This PR takes a number of small steps to improve the efficiency, focusing on the `Xml::MaskedMappings` class.
Before this PR, ~1250 repeating sections took ~95 seconds for mapping augmentation. This PR gets that down to ~5.8 seconds.
Some of the small steps...
- Frozen object reuse e.g. `DO_NOT_CAPTURE_MAPPING = { 'do_not_capture' => true }.freeze`
- Using `deep_dup` only when needed
- Pre-allocating Arrays and hash with exact size to avoid resizing operations
- Direct array assignment to avoid intermediate objects (e.g. `.map`)
- Where possible, using O(1) lookups instead of O(n) searches
- Use …
> Improve performance when handling large XML files with significant column augmentation
